[package]
name = "be-asset"
version = "0.0.0"
edition.workspace = true
description = "Asset Service - Logic for managing file assets"

[dependencies]
base64 = { workspace = true }
be-remote-db = { workspace = true }
be-storage = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
hex = { workspace = true }
prost-types = { workspace = true }
proto-gen = { workspace = true, features = ["server"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4", "v7"] }
