[package]
name = "agent-graph"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
description = "Agent graph library"
license = "MIT"

[dependencies]
agent-chain = { workspace = true }
agent-graph-macros = { workspace = true }
async-trait = { workspace = true }
futures.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
