[package]
name = "euro-auth"
version = "0.0.0"
edition.workspace = true

[package.metadata.cargo-machete]
ignored = ["specta"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
euro-proto-client = { workspace = true }
euro-secret = { workspace = true }
jsonwebtoken = "9.3"
serde = { workspace = true, features = ["std"] }
specta = { workspace = true, features = ["derive", "function"] }
taurpc = { version = "0.5.2" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
