[package]
name = "euro-auth"
version = "0.0.0"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = "0.1"
chrono = { workspace = true, features = ["serde"] }
euro-proto = { workspace = true }
euro-proto-client = { workspace = true }
euro-secret = { workspace = true }
jsonwebtoken = "9.3"
serde = { workspace = true, features = ["std"] }
serde_json = { version = "1.0", features = ["arbitrary_precision", "std"] }
specta = { workspace = true, features = ["derive", "function"] }
specta-typescript = { version = "0.0.9" }
tauri-specta = { version = "2.0.0-rc.21", features = [
  "javascript",
  "typescript",
] }
taurpc = { version = "0.5.1" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tonic = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
