[package]
name = "euro-personal-db"
version = "0.0.0"
authors.workspace = true
edition = "2024"
description = "Eurora Personal DB"

[dependencies]
anyhow.workspace = true
base64 = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
euro-secret = { workspace = true }
ferrous-llm-core = { workspace = true, features = ["specta"] }
futures = { workspace = true, features = ["std"] }
image = { workspace = true, default-features = false, features = [
  "jpeg",
  "png",
] }
libsqlite3-sys = { version = "0.30.1", features = [
  "bundled-sqlcipher-vendored-openssl",
] }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
specta = { workspace = true, features = [
  "chrono",
  "derive",
  "function",
] }
sqlite-vec = "0.1.3"
sqlx = { version = "0.8.6", features = [
  "chrono",
  "macros",
  "migrate",
  "runtime-tokio-rustls",
  "sqlite",
  "uuid",
] }
tokio = { workspace = true, features = ["full", "tracing"] }
tracing = { workspace = true }
uuid = { workspace = true }
zerocopy = { version = "0.8.31" }
