[package]
name = "proto-gen"
version = "0.0.0"
edition.workspace = true

[package.metadata.cargo-machete]
ignored = ["serde", "tonic-prost"]

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tonic = { workspace = true }
tonic-prost = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }

[features]
default = []
server = []
