[package]
name = "euro-vision"
version = "0.0.0"
license = "LicenseRef-Eurora-SUL-AND-Apache-2.0"
license-file = "LICENSE"
edition.workspace = true
description = "Vision util for capturing screen, window and ocr'ing"

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
image = { workspace = true }
tracing = { workspace = true }
xcap = { version = "0.7.0" }
