[package]
name = "euro-vision"
version = "0.0.0"
authors.workspace = true
edition = "2024"
description = "Vision util for capturing screen, window and ocr'ing"

[dependencies]
anyhow = { workspace = true }
base64.workspace = true
bytemuck = "1.24.0"
euro-ocr = { workspace = true }
futures-intrusive = "0.5.0"
image = { workspace = true }
pollster = "0.4.0"
rusty-tesseract = "1.1.10"
tokio = { workspace = true }
tracing = { workspace = true }
wgpu = "25.0.2"
xcap = { version = "0.7.0" }
