[package]
name = "euro-vision"
version = "0.0.0"
edition.workspace = true
description = "Vision util for capturing screen, window and ocr'ing"
license = "LicenseRef-Eurora-SUL-AND-Apache-2.0"

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
image = { workspace = true }
