[package]
name = "euro-vision"
version = "0.0.0"
edition.workspace = true
description = "Vision util for capturing screen, window and ocr'ing"

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
euro-ocr = { workspace = true }
image = { workspace = true }
tracing = { workspace = true }
xcap = { version = "0.7.0" }
