[package]
name = "euro-proto"
version = "0.0.0"
authors.workspace = true
edition = "2024"

[package.metadata.cargo-machete]
ignored = ["serde", "tonic-prost"]

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
