[package]
name = "euro-proto"
version = "0.0.0"
authors.workspace = true
edition = "2024"

[dependencies]
anyhow = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
specta = { workspace = true, features = ["derive", "function"] }
tokio = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
