[package]
name = "euro-native-messaging"
version = "0.0.0"
edition.workspace = true
license = "LicenseRef-Eurora-SUL-AND-Apache-2.0"

[package.metadata.cargo-machete]
ignored = ["tonic-prost"]

[dependencies]
anyhow = { workspace = true }
async-stream = "0.3"
backon = { workspace = true }
base64 = { workspace = true }
enum_dispatch = { workspace = true }
euro-process = { workspace = true }
image = { workspace = true, features = ["default"] }
prost = { workspace = true }
prost-types = { workspace = true }
resvg = { version = "0.45" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
specta = { workspace = true, features = [
  "derive",
  "export",
  "function",
  "serde",
  "serde_json"
] }
specta-typescript = { version = "0.0.9" }
strum_macros = { workspace = true }
tiny-skia = "0.11"
tokio = { workspace = true, features = ["full"] }
tonic = { workspace = true, features = [
  "channel",
  "router",
  "server",
  "tls-native-roots"
] }
tonic-prost = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
usvg = { version = "0.45", default-features = true }

[build-dependencies]
tonic-prost-build = { workspace = true }

[target.'cfg(windows)'.dependencies]
winreg = "0.55"

[lints.clippy]
all = "deny"
correctness = "deny"
perf = "deny"
