[package]
name = "be-authz"
version = "0.0.0"
edition.workspace = true
license = "LicenseRef-Eurora-SUL-AND-Apache-2.0"

[dependencies]
auth-core = { workspace = true }
axum = { workspace = true }
be-auth-core = { workspace = true }
casbin = { workspace = true }
http = "1"
pin-project-lite = "0.2"
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true, features = ["util"] }
tracing = { workspace = true }
