[package]
name = "euro-ocr-service"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
euro-auth = { workspace = true }
euro-ocr = { workspace = true }
euro-proto = { workspace = true }
futures = { workspace = true }
image = { workspace = true }
prost = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
