[package]
name = "asset-models"
version = "0.0.0"
edition.workspace = true
description = "Shared models and functions"

[package.metadata.cargo-machete]
ignored = ["tonic-prost"]

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
