[package]
name = "euro-auth-service"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
bcrypt = "0.17"
be-auth-grpc = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
euro-auth = { workspace = true }
euro-proto = { workspace = true }
euro-remote-db = { workspace = true }
hex = "0.4.3"
jsonwebtoken = { workspace = true }
oauth2 = "5.0.0"
prost = { workspace = true }
rand = { workspace = true }
reqwest = { version = "0.12", features = ["json"] }
serde = { workspace = true, features = ["derive"] }
sha2 = "0.10"
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
tonic = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }

[build-dependencies]
tonic-prost-build = { workspace = true }
