[package]
name = "be-auth-core"
version = "0.0.0"
license = "LicenseRef-Eurora-SUL-AND-Apache-2.0"
license-file = "LICENSE"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
auth-core = { workspace = true }
jsonwebtoken = { workspace = true }
