[package]
name = "be-auth-core"
version = "0.0.0"
edition.workspace = true
license = "LicenseRef-Eurora-SUL-AND-Apache-2.0"

[dependencies]
anyhow = { workspace = true }
auth-core = { workspace = true }
jsonwebtoken = { workspace = true }
