[package]
name = "be-auth-core"
version = "0.0.0"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
auth-core = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
euro-remote-db = { workspace = true }
jsonwebtoken = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }
