[package]
name = "be-conversation-service"
version = "0.0.0"
edition.workspace = true

[package.metadata.cargo-machete]
ignored = ["tonic-prost"]

[dependencies]
activity-models = { workspace = true }
asset-models = { workspace = true }
be-asset = { workspace = true }
be-auth-grpc = { workspace = true }
be-remote-db = { workspace = true }
be-storage = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
prost = { workspace = true }
prost-types = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["serde", "v7"] }

[build-dependencies]
tonic-prost-build = { workspace = true }
