[package]
name = "euro-activity-service"
version = "0.0.0"
edition.workspace = true

[package.metadata.cargo-machete]
ignored = ["tonic-prost"]

[dependencies]
activity-models = { workspace = true }
anyhow = { workspace = true }
be-auth-grpc = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
euro-remote-db = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }

[build-dependencies]
tonic-prost-build = { workspace = true }
