[package]
name = "be-monolith"
version = "0.0.1"
edition.workspace = true
license = "LicenseRef-Eurora-SUL-AND-Apache-2.0"
publish = false

[dependencies]
axum = { workspace = true }
be-activity-service = { workspace = true }
be-asset = { workspace = true }
be-asset-service = { workspace = true }
be-auth-core = { workspace = true }
be-auth-service = { workspace = true }
be-authz = { workspace = true }
be-local-settings = { workspace = true }
be-local-settings-service = { workspace = true }
be-payment-service = { workspace = true }
be-remote-db = { workspace = true }
be-storage = { workspace = true, features = ["encryption"] }
be-thread-service = { workspace = true }
be-update-service = { workspace = true }
dotenv = { workspace = true }
posthog-rs = { workspace = true }
prost = { workspace = true }
proto-gen = { workspace = true }
sentry = { workspace = true, features = ["tracing"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
tonic = { workspace = true }
tonic-health = "0.14.3"
tonic-web = "0.14.3"
tower-http = { version = "0.6.8", features = ["cors"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }

[build-dependencies]
tonic-prost-build = { workspace = true }
