[package]
name = "euro-prompt-kit"
version = "0.0.0"
authors.workspace = true
edition = "2024"

[dependencies]
agent-chain = { workspace = true }
agent-graph = { workspace = true }
anyhow = { workspace = true }
async_from = { workspace = true }
euro-llm = { workspace = true }
euro-llm-eurora = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
