[package]
name = "euro-prompt-kit"
version = "0.0.0"
authors.workspace = true
edition = "2024"

[dependencies]
anyhow = { workspace = true }
# euro-proto-client = { workspace = true }
async_from = { workspace = true }
euro-llm = { workspace = true }
euro-llm-eurora = { workspace = true }
euro-proto = { workspace = true }
futures = { workspace = true }
image = { workspace = true }
regex = "1.12.2"
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
