[package]
name = "euro-user"
version = "0.0.0"
edition.workspace = true
license = "LicenseRef-Eurora-SUL-AND-Apache-2.0"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
euro-auth = { workspace = true }
euro-secret = { workspace = true }
euro-storage = { workspace = true }
serde = { workspace = true, features = ["std"] }
serde_json = { workspace = true, features = ["arbitrary_precision", "std"] }
uuid = { workspace = true, features = ["serde"] }
