[package]
name = "euro-user"
version = "0.0.0"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
auth-core = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
euro-proto-client = { workspace = true }
euro-secret = { workspace = true }
euro-storage = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["std"] }
serde_json = { version = "1.0", features = ["arbitrary_precision", "std"] }
sha2 = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
