[package]
name = "eur-prompt-kit"
version = "0.0.0"
edition = "2024"
authors.workspace = true

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
image = { workspace = true }
ferrous-llm = { workspace = true, features = ["openai", "ollama", "anthropic"] }
eur-eurora-provider = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
thiserror = { workspace = true }
eur-util = { workspace = true }
regex = "1.12.2"
tracing = { workspace = true }
eur-proto = { workspace = true }
# eur-proto-client = { workspace = true }
async_from = { workspace = true }
