[package]
name = "eur-prompt-kit"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
image = { workspace = true }
llm = { git = "https://github.com/AndreRoelofs/llm.git", branch = "main", features = ["openai"] }
# llm = { version = "1.2.4", features = ["openai"] }
openai-api-rs = { git = "https://github.com/AndreRoelofs/openai-api-rs.git", branch = "main" }
tokio = { workspace = true }
eur-util = { workspace = true }
regex = "1.9.6"
tracing = { workspace = true }
reqwest = "0.12"
