[package]
name = "euro-proto-client"
version = "0.0.0"
edition.workspace = true
description = "Eurora gRPC client"
publish = false

[dependencies]
anyhow = { workspace = true }
euro-proto = { workspace = true }
tonic = { workspace = true, features = ["channel", "tls-native-roots"] }
tracing = { workspace = true }
