[package]
name = "be-storage"
version = "0.0.0"
edition.workspace = true
description = "Eurora Storage API"

[dependencies]
anyhow = { workspace = true }
hex = { version = "0.4" }
opendal = { version = "0.55.0", features = ["services-fs", "services-s3"] }
sha2 = { version = "0.10" }
tracing = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4", "v7"] }
