[package]
name = "be-storage"
version = "0.0.0"
edition.workspace = true
description = "Eurora Storage API"
license = "LicenseRef-Eurora-SUL-AND-Apache-2.0"

[dependencies]
hex = { workspace = true }
opendal = { version = "0.55.0", features = ["services-fs", "services-s3"] }
sha2 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4", "v7"] }
