[package]
name = "auth-core"
version = "0.0.0"
edition.workspace = true
license = "LicenseRef-Eurora-SUL-AND-Apache-2.0"
license-file = "LICENSE"

[dependencies]
serde = { workspace = true, features = ["std"] }
specta = { workspace = true, optional = true }

[features]
specta = ["specta/derive", "specta/function"]
