[package]
name = "euro-llm-core"
version = "0.6.1"
authors.workspace = true
edition.workspace = true
description = "Core LLM library"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
async-trait = "0.1"
base64 = { workspace = true, optional = true }
chrono = { workspace = true, features = ["serde"] }
futures = { workspace = true }
image = { workspace = true, features = ["jpeg", "png"], optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
specta = { version = "2.0.0-rc.22", features = [
  "chrono",
  "derive",
  "serde",
  "serde_json",
], optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
url = { workspace = true, features = ["serde"] }

[features]
dynamic-image = ["base64", "image"]
specta = ["dep:specta"]
