[package]
name = "euro-monolith"
version = "0.0.1"
edition.workspace = true
publish = false

[dependencies]
axum = "0.8.8"
be-auth-grpc = { workspace = true }
dotenv = { workspace = true }
euro-activity-service = { workspace = true, features = ["server"] }
euro-assets-service = { workspace = true, features = ["server"] }
euro-auth-service = { workspace = true }
euro-prompt-service = { workspace = true }
euro-proto = { workspace = true }
euro-remote-db = { workspace = true }
euro-update-service = { workspace = true }
prost = { workspace = true }
sentry = { workspace = true, features = ["log", "logs", "tracing"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
tonic = { workspace = true }
tonic-health = "0.14.2"
tonic-web = "0.14.2"
tower-http = { version = "0.6.8", features = ["cors"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }

[build-dependencies]
tonic-prost-build = { workspace = true }
