[package]
name = "euro-monolith"
version = "0.0.1"
edition = "2024"
authors = ["Eurora <eurora@company.com>"]
publish = false

[dependencies]
anyhow = { workspace = true }
axum = "0.8.7"
dotenv = "0.15"
euro-auth = { workspace = true }
euro-auth-service = { workspace = true }
euro-ocr-service = { workspace = true }
euro-prompt-service = { workspace = true }
euro-proto = { workspace = true }
euro-remote-db = { workspace = true }
euro-update-service = { workspace = true }
futures = "0.3"
image = { workspace = true }
prost = { workspace = true }
sentry = { workspace = true, features = ["log", "logs", "tracing"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
tonic = { workspace = true }
tonic-health = "0.14.2"
tonic-web = "0.14.2"
tower = "0.5.2"
tower-http = { version = "0.6.7", features = ["cors"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }

[build-dependencies]
tonic-prost-build = { workspace = true }
