[package]
name = "focus-tracker"
version = "0.0.2"
edition.workspace = true
description = "Cross-platform focus tracker for Linux (X11), macOS and Windows"
homepage = "https://github.com/eurora-labs/eurora/tree/main/crates/common/focus-tracker"
repository = "https://github.com/eurora-labs/eurora.git"
license = "Apache-2.0"
keywords = [
  "application",
  "desktop",
  "focus-tracker",
  "window-focus-tracker",
  "window-manager",
]

[dependencies]
focus-tracker-core = { workspace = true }
image = { workspace = true }
# Optional async dependencies
tokio = { workspace = true, features = [
  "fs",
  "io-util",
  "macros",
  "rt",
  "rt-multi-thread",
  "sync",
  "time",
], optional = true }
tracing = { workspace = true }

[dev-dependencies]
ctrlc = "3.4.5"
image = { workspace = true }
serial_test = "3.3.1"
tracing-subscriber = { workspace = true }
winit = "0.30.5"

[target.'cfg(target_os = "linux")'.dependencies]
x11rb = "0.13.1"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.3"
objc2-app-kit = "0.3.2"
objc2-foundation = "0.3.2"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.61.1", features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_System_ProcessStatus",
  "Win32_System_StationsAndDesktops",
  "Win32_System_Threading",
  "Win32_UI_Accessibility",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
] }

[features]
async = [
  "tokio",
]
