[package]
name = "agent-chain"
version = "0.0.2"
edition.workspace = true
description = "Agent chain library"
license = "MIT"

[dependencies]
agent-chain-core = { workspace = true }
agent-chain-macros = { workspace = true }
async-stream = { workspace = true }
async-trait = { workspace = true }
backon = { workspace = true }
base64 = { workspace = true }
futures = { workspace = true }
percent-encoding = { workspace = true }
reqwest = { version = "0.12", features = ["json", "stream"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
tracing = { workspace = true }
url = { workspace = true }

[features]
default = ["anthropic", "ollama", "openai"]
anthropic = []
ollama = []
openai = []

[dev-dependencies]
dotenv = { workspace = true }

[[test]]
name = "openai"
path = "tests/openai/mod.rs"

[[test]]
name = "ollama"
path = "tests/ollama/mod.rs"
