[package]
name = "agent-chain"
version = "0.0.1"
authors.workspace = true
edition.workspace = true
description = "Agent chain library"
license = "MIT"

[dependencies]
agent-chain-macros = "0.0.1"
async-stream = "0.3"
async-trait = { workspace = true }
futures.workspace = true
reqwest = { version = "0.12", features = ["json", "stream"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
specta = { workspace = true, features = [
  "derive",
  "serde",
  "serde_json",
], optional = true }
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
uuid = { workspace = true, features = ["v4"] }

[features]
default = []
anthropic = []
ollama = []
openai = []
specta = ["dep:specta"]
