[package]
name = "euro-fs"
version = "0.0.0"
authors.workspace = true
edition = "2024"
publish = false

[dependencies]
anyhow = { workspace = true }
bstr = { workspace = true }
serde = { workspace = true, features = ["std"] }
toml = { workspace = true }
walkdir = "2.5.0"
