[package]
name = "be-local-settings"
version = "0.0.0"
edition.workspace = true
license = "LicenseRef-Eurora-SUL-AND-Apache-2.0"

[dependencies]
proto-gen = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
url = { workspace = true }

[features]
default = []
server = ["proto-gen/server"]
