[package]
name = "agent-chain-core"
version = "0.0.3"
edition.workspace = true
description = "Core library for agent-chain crate"
license = "MIT"

[dependencies]
async-stream = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bon = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
csv = "1.3"
# enum_dispatch = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }
regex = { workspace = true }
reqwest = { version = "0.12", features = ["json", "stream"] }
rust-sugiyama = "0.4"
rustc_version_runtime = "0.3.0"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1", features = ["sync"] }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4", "v7"] }

[dev-dependencies]
serial_test = "3"
tempfile = { workspace = true }
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread", "time"] }

[features]
default = []
