[package]
name = "euro-screen-position"
version = "0.0.0"
edition.workspace = true

[dependencies]
enigo = "0.6.1"
tauri = { version = "^2.9.5", features = ["tray-icon", "unstable"] }
xcap = { version = "0.7.0" }
