no-clearly-defined = true
private = { ignore = true }

accepted = [
  "Apache-2.0",
  "MIT",
  "MIT-0",
  "Apache-2.0 WITH LLVM-exception",
  "MPL-2.0",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "ISC",
  "CC0-1.0",
  "NCSA",
  "Unicode-3.0",
  "OpenSSL",
  "Zlib",
  "BSL-1.0",
  # Custom license for Eurora crates
  "LicenseRef-Eurora-SUL-AND-Apache-2.0",
  "CDLA-Permissive-2.0"
]

[dlopen2.clarify]
license = "MIT"

[dlopen2_derive.clarify]
license = "MIT"