[package]
name = "be-auth-service"
version = "0.0.0"
edition.workspace = true
license = "LicenseRef-Eurora-SUL-AND-Apache-2.0"
publish = false

[dependencies]
anyhow = { workspace = true }
auth-core = { workspace = true }
base64 = { workspace = true }
bcrypt = "0.17"
be-auth-grpc = { workspace = true }
be-remote-db = { workspace = true }
chacha20poly1305 = "0.10"
chrono = { workspace = true, features = ["serde"] }
hex = { workspace = true }
jsonwebtoken = { workspace = true }
oauth2 = "5.0.0"
prost = { workspace = true }
proto-gen = { workspace = true, features = ["server"] }
rand = { workspace = true }
reqwest = { version = "0.12", features = ["json"] }
serde = { workspace = true, features = ["derive"] }
sha2 = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }

[build-dependencies]
tonic-prost-build = { workspace = true }
