[package]
name = "be-auth-service"
version = "0.0.0"
edition.workspace = true
license = "LicenseRef-Eurora-SUL-AND-Apache-2.0"
publish = false

[dependencies]
argon2 = { workspace = true }
auth-core = { workspace = true }
be-auth-core = { workspace = true }
bon = { workspace = true }
be-remote-db = { workspace = true }
chacha20poly1305 = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
hex = { workspace = true }
jsonwebtoken = { workspace = true }
openidconnect = { workspace = true }
percent-encoding = { workspace = true }
prost = { workspace = true }
proto-gen = { workspace = true, features = ["server"] }
rand = { workspace = true }
reqwest = { version = "0.12", features = ["json"] }
serde = { workspace = true, features = ["derive"] }
sha2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }

[build-dependencies]
tonic-prost-build = { workspace = true }
