[package]
name = "be-auth-grpc"
version = "0.0.0"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
be-auth-core = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
euro-auth = { workspace = true }
euro-remote-db = { workspace = true }
jsonwebtoken = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }
