[package]
name = "be-auth-grpc"
version = "0.0.0"
edition.workspace = true

[package.metadata.cargo-machete]
ignored = ["tonic-prost"]

[dependencies]
be-auth-core = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }
