[package]
name = "euro-secret"
version = "0.0.0"
license = "LicenseRef-Eurora-SUL-AND-Apache-2.0"
license-file = "LICENSE"
edition.workspace = true
description = "Secret management for Eurora"

[dependencies]
anyhow = { workspace = true }
keyring = { workspace = true, features = [
  "apple-native",
  "crypto-rust",
  "linux-native",
  "windows-native",
] }
serde = { workspace = true, features = ["std"] }
