[package]
name = "euro-secret"
version = "0.0.0"
edition.workspace = true
description = "Secret management for Eurora"
license = "LicenseRef-Eurora-SUL-AND-Apache-2.0"

[dependencies]
anyhow = { workspace = true }
chacha20poly1305 = { workspace = true, features = ["std"] }
co-utils = { workspace = true }
keyring = { workspace = true, features = [
  "apple-native",
  "crypto-rust",
  "linux-native-sync-persistent",
  "windows-native",
] }
rand = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
zeroize = { workspace = true }
