[package]
name = "agent-graph-macros"
version = "0.0.2"
edition.workspace = true
description = "Procedural macros for agent-graph"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["extra-traits", "full"] }
