[package]
name = "euro-update-service"
version = "0.0.0"
edition.workspace = true
description = "Eurora Update Service"
publish = false

[dependencies]
anyhow = { workspace = true }
aws-config = { version = "1.8.7", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.107.0"
axum = { version = "0.8.7", features = ["macros"] }
chrono = { workspace = true, features = ["serde"] }
futures = { workspace = true, features = ["std"] }
semver = "1.0"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full", "tracing"] }
tower = "0.5.2"
tower-http = { version = "0.6.7", features = ["cors", "trace"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }
