[package]
name = "be-update-service"
version = "0.0.0"
edition.workspace = true
description = "Eurora Update Service"
license = "LicenseRef-Eurora-SUL-AND-Apache-2.0"
publish = false

[dependencies]
anyhow = { workspace = true }
aws-config = { version = "1.8.12", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.121.0"
axum = { workspace = true, features = ["macros"] }
chrono = { workspace = true, features = ["serde"] }
semver = "1.0"
serde = { workspace = true, features = ["derive"] }
posthog-rs = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
tower = { workspace = true }
tower-http = { version = "0.6.8", features = ["cors", "trace"] }
tracing = { workspace = true }
