[package]
name = "be-remote-db"
version = "0.0.0"
edition.workspace = true
description = "Eurora Remote DB"
license = "LicenseRef-Eurora-SUL-AND-Apache-2.0"

[dependencies]
bon = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
ipnet = { version = "2", features = ["serde"] }
prost-types = { workspace = true }
proto-gen = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlx = { version = "0.8.6", features = [
  "chrono",
  "ipnet",
  "json",
  "migrate",
  "postgres",
  "runtime-tokio",
  "tls-rustls-aws-lc-rs",
  "uuid",
] }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["serde", "v7"] }
